// Code generated by MockGen. DO NOT EDIT.
// Source: impl.go
//
// Generated by this command:
//
//	mockgen -source=impl.go -destination=../../tests/mocks/ports.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/rickferrdev/gostock/internal/core/domain"
	ports "github.com/rickferrdev/gostock/internal/core/ports"
	gomock "go.uber.org/mock/gomock"
)

// MockStockRepository is a mock of StockRepository interface.
type MockStockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStockRepositoryMockRecorder
	isgomock struct{}
}

// MockStockRepositoryMockRecorder is the mock recorder for MockStockRepository.
type MockStockRepositoryMockRecorder struct {
	mock *MockStockRepository
}

// NewMockStockRepository creates a new mock instance.
func NewMockStockRepository(ctrl *gomock.Controller) *MockStockRepository {
	mock := &MockStockRepository{ctrl: ctrl}
	mock.recorder = &MockStockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStockRepository) EXPECT() *MockStockRepositoryMockRecorder {
	return m.recorder
}

// All mocks base method.
func (m *MockStockRepository) All(ctx context.Context) ([]*domain.Stock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "All", ctx)
	ret0, _ := ret[0].([]*domain.Stock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// All indicates an expected call of All.
func (mr *MockStockRepositoryMockRecorder) All(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "All", reflect.TypeOf((*MockStockRepository)(nil).All), ctx)
}

// ByID mocks base method.
func (m *MockStockRepository) ByID(ctx context.Context, id string) (*domain.Stock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ByID", ctx, id)
	ret0, _ := ret[0].(*domain.Stock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ByID indicates an expected call of ByID.
func (mr *MockStockRepositoryMockRecorder) ByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ByID", reflect.TypeOf((*MockStockRepository)(nil).ByID), ctx, id)
}

// Create mocks base method.
func (m *MockStockRepository) Create(ctx context.Context, stock *domain.Stock) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, stock)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockStockRepositoryMockRecorder) Create(ctx, stock any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockStockRepository)(nil).Create), ctx, stock)
}

// Delete mocks base method.
func (m *MockStockRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockStockRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockStockRepository)(nil).Delete), ctx, id)
}

// Update mocks base method.
func (m *MockStockRepository) Update(ctx context.Context, stock *domain.Stock) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, stock)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockStockRepositoryMockRecorder) Update(ctx, stock any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockStockRepository)(nil).Update), ctx, stock)
}

// MockStockService is a mock of StockService interface.
type MockStockService struct {
	ctrl     *gomock.Controller
	recorder *MockStockServiceMockRecorder
	isgomock struct{}
}

// MockStockServiceMockRecorder is the mock recorder for MockStockService.
type MockStockServiceMockRecorder struct {
	mock *MockStockService
}

// NewMockStockService creates a new mock instance.
func NewMockStockService(ctrl *gomock.Controller) *MockStockService {
	mock := &MockStockService{ctrl: ctrl}
	mock.recorder = &MockStockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStockService) EXPECT() *MockStockServiceMockRecorder {
	return m.recorder
}

// All mocks base method.
func (m *MockStockService) All(ctx context.Context) ([]*domain.Stock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "All", ctx)
	ret0, _ := ret[0].([]*domain.Stock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// All indicates an expected call of All.
func (mr *MockStockServiceMockRecorder) All(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "All", reflect.TypeOf((*MockStockService)(nil).All), ctx)
}

// AvailableSpace mocks base method.
func (m *MockStockService) AvailableSpace(ctx context.Context, id string) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AvailableSpace", ctx, id)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AvailableSpace indicates an expected call of AvailableSpace.
func (mr *MockStockServiceMockRecorder) AvailableSpace(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AvailableSpace", reflect.TypeOf((*MockStockService)(nil).AvailableSpace), ctx, id)
}

// ByID mocks base method.
func (m *MockStockService) ByID(ctx context.Context, id string) (*domain.Stock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ByID", ctx, id)
	ret0, _ := ret[0].(*domain.Stock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ByID indicates an expected call of ByID.
func (mr *MockStockServiceMockRecorder) ByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ByID", reflect.TypeOf((*MockStockService)(nil).ByID), ctx, id)
}

// Create mocks base method.
func (m *MockStockService) Create(ctx context.Context, stock *domain.Stock) (*domain.Stock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, stock)
	ret0, _ := ret[0].(*domain.Stock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockStockServiceMockRecorder) Create(ctx, stock any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockStockService)(nil).Create), ctx, stock)
}

// Occupancy mocks base method.
func (m *MockStockService) Occupancy(ctx context.Context, id string) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Occupancy", ctx, id)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Occupancy indicates an expected call of Occupancy.
func (mr *MockStockServiceMockRecorder) Occupancy(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Occupancy", reflect.TypeOf((*MockStockService)(nil).Occupancy), ctx, id)
}

// Remove mocks base method.
func (m *MockStockService) Remove(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockStockServiceMockRecorder) Remove(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockStockService)(nil).Remove), ctx, id)
}

// Update mocks base method.
func (m *MockStockService) Update(ctx context.Context, stock *domain.Stock) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, stock)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockStockServiceMockRecorder) Update(ctx, stock any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockStockService)(nil).Update), ctx, stock)
}

// ValidateStock mocks base method.
func (m *MockStockService) ValidateStock(stock *domain.Stock) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateStock", stock)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateStock indicates an expected call of ValidateStock.
func (mr *MockStockServiceMockRecorder) ValidateStock(stock any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateStock", reflect.TypeOf((*MockStockService)(nil).ValidateStock), stock)
}

// MockProductRepository is a mock of ProductRepository interface.
type MockProductRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProductRepositoryMockRecorder
	isgomock struct{}
}

// MockProductRepositoryMockRecorder is the mock recorder for MockProductRepository.
type MockProductRepositoryMockRecorder struct {
	mock *MockProductRepository
}

// NewMockProductRepository creates a new mock instance.
func NewMockProductRepository(ctrl *gomock.Controller) *MockProductRepository {
	mock := &MockProductRepository{ctrl: ctrl}
	mock.recorder = &MockProductRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductRepository) EXPECT() *MockProductRepositoryMockRecorder {
	return m.recorder
}

// ByID mocks base method.
func (m *MockProductRepository) ByID(ctx context.Context, id string) (*domain.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ByID", ctx, id)
	ret0, _ := ret[0].(*domain.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ByID indicates an expected call of ByID.
func (mr *MockProductRepositoryMockRecorder) ByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ByID", reflect.TypeOf((*MockProductRepository)(nil).ByID), ctx, id)
}

// ByStockID mocks base method.
func (m *MockProductRepository) ByStockID(ctx context.Context, id string) ([]*domain.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ByStockID", ctx, id)
	ret0, _ := ret[0].([]*domain.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ByStockID indicates an expected call of ByStockID.
func (mr *MockProductRepositoryMockRecorder) ByStockID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ByStockID", reflect.TypeOf((*MockProductRepository)(nil).ByStockID), ctx, id)
}

// CreateAtomic mocks base method.
func (m *MockProductRepository) CreateAtomic(ctx context.Context, product *domain.Product) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAtomic", ctx, product)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAtomic indicates an expected call of CreateAtomic.
func (mr *MockProductRepositoryMockRecorder) CreateAtomic(ctx, product any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAtomic", reflect.TypeOf((*MockProductRepository)(nil).CreateAtomic), ctx, product)
}

// Delete mocks base method.
func (m *MockProductRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockProductRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockProductRepository)(nil).Delete), ctx, id)
}

// UpdateAtomic mocks base method.
func (m *MockProductRepository) UpdateAtomic(ctx context.Context, product *domain.Product) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAtomic", ctx, product)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAtomic indicates an expected call of UpdateAtomic.
func (mr *MockProductRepositoryMockRecorder) UpdateAtomic(ctx, product any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAtomic", reflect.TypeOf((*MockProductRepository)(nil).UpdateAtomic), ctx, product)
}

// MockProductService is a mock of ProductService interface.
type MockProductService struct {
	ctrl     *gomock.Controller
	recorder *MockProductServiceMockRecorder
	isgomock struct{}
}

// MockProductServiceMockRecorder is the mock recorder for MockProductService.
type MockProductServiceMockRecorder struct {
	mock *MockProductService
}

// NewMockProductService creates a new mock instance.
func NewMockProductService(ctrl *gomock.Controller) *MockProductService {
	mock := &MockProductService{ctrl: ctrl}
	mock.recorder = &MockProductServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductService) EXPECT() *MockProductServiceMockRecorder {
	return m.recorder
}

// ByID mocks base method.
func (m *MockProductService) ByID(ctx context.Context, id string) (*domain.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ByID", ctx, id)
	ret0, _ := ret[0].(*domain.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ByID indicates an expected call of ByID.
func (mr *MockProductServiceMockRecorder) ByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ByID", reflect.TypeOf((*MockProductService)(nil).ByID), ctx, id)
}

// ByStockID mocks base method.
func (m *MockProductService) ByStockID(ctx context.Context, id string) ([]*domain.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ByStockID", ctx, id)
	ret0, _ := ret[0].([]*domain.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ByStockID indicates an expected call of ByStockID.
func (mr *MockProductServiceMockRecorder) ByStockID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ByStockID", reflect.TypeOf((*MockProductService)(nil).ByStockID), ctx, id)
}

// Create mocks base method.
func (m *MockProductService) Create(ctx context.Context, product *domain.Product) (*domain.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, product)
	ret0, _ := ret[0].(*domain.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockProductServiceMockRecorder) Create(ctx, product any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockProductService)(nil).Create), ctx, product)
}

// Delete mocks base method.
func (m *MockProductService) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockProductServiceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockProductService)(nil).Delete), ctx, id)
}

// Errors mocks base method.
func (m *MockProductService) Errors(err error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Errors", err)
	ret0, _ := ret[0].(error)
	return ret0
}

// Errors indicates an expected call of Errors.
func (mr *MockProductServiceMockRecorder) Errors(err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Errors", reflect.TypeOf((*MockProductService)(nil).Errors), err)
}

// Update mocks base method.
func (m *MockProductService) Update(ctx context.Context, product *domain.Product) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, product)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockProductServiceMockRecorder) Update(ctx, product any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockProductService)(nil).Update), ctx, product)
}

// ValidateID mocks base method.
func (m *MockProductService) ValidateID(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateID", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateID indicates an expected call of ValidateID.
func (mr *MockProductServiceMockRecorder) ValidateID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateID", reflect.TypeOf((*MockProductService)(nil).ValidateID), id)
}

// ValidateProduct mocks base method.
func (m *MockProductService) ValidateProduct(product *domain.Product) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateProduct", product)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateProduct indicates an expected call of ValidateProduct.
func (mr *MockProductServiceMockRecorder) ValidateProduct(product any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateProduct", reflect.TypeOf((*MockProductService)(nil).ValidateProduct), product)
}

// MockHealthService is a mock of HealthService interface.
type MockHealthService struct {
	ctrl     *gomock.Controller
	recorder *MockHealthServiceMockRecorder
	isgomock struct{}
}

// MockHealthServiceMockRecorder is the mock recorder for MockHealthService.
type MockHealthServiceMockRecorder struct {
	mock *MockHealthService
}

// NewMockHealthService creates a new mock instance.
func NewMockHealthService(ctrl *gomock.Controller) *MockHealthService {
	mock := &MockHealthService{ctrl: ctrl}
	mock.recorder = &MockHealthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHealthService) EXPECT() *MockHealthServiceMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockHealthService) Check(ctx context.Context) *ports.HealthResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", ctx)
	ret0, _ := ret[0].(*ports.HealthResponse)
	return ret0
}

// Check indicates an expected call of Check.
func (mr *MockHealthServiceMockRecorder) Check(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockHealthService)(nil).Check), ctx)
}
