// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/products": {
            "post": {
                "description": "Creates a new product and associates it with a stock",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Create a product",
                "parameters": [
                    {
                        "description": "Product payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_rickferrdev_gostock_internal_core_ports.DTORequestCreateProduct"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_rickferrdev_gostock_internal_core_ports.DTOResponseCreateProduct"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/github_com_rickferrdev_gostock_internal_core_ports.Error"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_rickferrdev_gostock_internal_core_ports.Error"
                        }
                    }
                }
            }
        },
        "/products/{id}": {
            "get": {
                "description": "Returns a single product by its unique identifier",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Get a product by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Product ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_rickferrdev_gostock_internal_core_ports.DTOResponseByIDProduct"
                        }
                    },
                    "400": {
                        "description": "Missing or invalid product ID",
                        "schema": {
                            "$ref": "#/definitions/github_com_rickferrdev_gostock_internal_core_ports.Error"
                        }
                    },
                    "404": {
                        "description": "Product not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_rickferrdev_gostock_internal_core_ports.Error"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_rickferrdev_gostock_internal_core_ports.Error"
                        }
                    }
                }
            },
            "put": {
                "description": "Updates an existing product's fields by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Update a product",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Product ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated product payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_rickferrdev_gostock_internal_core_ports.DTORequestUpdateProduct"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Product updated successfully"
                    },
                    "400": {
                        "description": "Missing or invalid product ID / request body",
                        "schema": {
                            "$ref": "#/definitions/github_com_rickferrdev_gostock_internal_core_ports.Error"
                        }
                    },
                    "404": {
                        "description": "Product not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_rickferrdev_gostock_internal_core_ports.Error"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_rickferrdev_gostock_internal_core_ports.Error"
                        }
                    }
                }
            },
            "delete": {
                "description": "Permanently removes a product by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Delete a product",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Product ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Product deleted successfully"
                    },
                    "400": {
                        "description": "Missing or invalid product ID",
                        "schema": {
                            "$ref": "#/definitions/github_com_rickferrdev_gostock_internal_core_ports.Error"
                        }
                    },
                    "404": {
                        "description": "Product not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_rickferrdev_gostock_internal_core_ports.Error"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_rickferrdev_gostock_internal_core_ports.Error"
                        }
                    }
                }
            }
        },
        "/stocks": {
            "get": {
                "description": "Returns a list of all available stocks with their current capacity usage",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stocks"
                ],
                "summary": "List all stocks",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_rickferrdev_gostock_internal_core_ports.DTOResponseAllStock"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_rickferrdev_gostock_internal_core_ports.Error"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new stock with the given name and total capacity",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stocks"
                ],
                "summary": "Create a stock",
                "parameters": [
                    {
                        "description": "Stock payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_rickferrdev_gostock_internal_core_ports.DTORequestCreateStock"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_rickferrdev_gostock_internal_core_ports.DTOResponseCreateStock"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/github_com_rickferrdev_gostock_internal_core_ports.Error"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_rickferrdev_gostock_internal_core_ports.Error"
                        }
                    }
                }
            }
        },
        "/stocks/{id}": {
            "get": {
                "description": "Returns a single stock with its current occupancy by its unique identifier",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stocks"
                ],
                "summary": "Get a stock by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Stock ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_rickferrdev_gostock_internal_core_ports.DTOResponseByIDStock"
                        }
                    },
                    "400": {
                        "description": "Missing or invalid stock ID",
                        "schema": {
                            "$ref": "#/definitions/github_com_rickferrdev_gostock_internal_core_ports.Error"
                        }
                    },
                    "404": {
                        "description": "Stock not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_rickferrdev_gostock_internal_core_ports.Error"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_rickferrdev_gostock_internal_core_ports.Error"
                        }
                    }
                }
            },
            "put": {
                "description": "Updates the name and/or capacity of an existing stock by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stocks"
                ],
                "summary": "Update a stock",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Stock ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated stock payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_rickferrdev_gostock_internal_core_ports.DTORequestUpdateStock"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Stock updated successfully"
                    },
                    "400": {
                        "description": "Missing or invalid stock ID / request body",
                        "schema": {
                            "$ref": "#/definitions/github_com_rickferrdev_gostock_internal_core_ports.Error"
                        }
                    },
                    "404": {
                        "description": "Stock not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_rickferrdev_gostock_internal_core_ports.Error"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_rickferrdev_gostock_internal_core_ports.Error"
                        }
                    }
                }
            },
            "delete": {
                "description": "Permanently removes a stock by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stocks"
                ],
                "summary": "Delete a stock",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Stock ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Stock deleted successfully"
                    },
                    "400": {
                        "description": "Missing or invalid stock ID",
                        "schema": {
                            "$ref": "#/definitions/github_com_rickferrdev_gostock_internal_core_ports.Error"
                        }
                    },
                    "404": {
                        "description": "Stock not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_rickferrdev_gostock_internal_core_ports.Error"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_rickferrdev_gostock_internal_core_ports.Error"
                        }
                    }
                }
            }
        },
        "/stocks/{id}/products": {
            "get": {
                "description": "Returns all products associated with a given stock ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "List products by stock",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Stock ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_rickferrdev_gostock_internal_core_ports.DTOResponseByStockIDProduct"
                        }
                    },
                    "400": {
                        "description": "Missing or invalid stock ID",
                        "schema": {
                            "$ref": "#/definitions/github_com_rickferrdev_gostock_internal_core_ports.Error"
                        }
                    },
                    "404": {
                        "description": "Stock not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_rickferrdev_gostock_internal_core_ports.Error"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_rickferrdev_gostock_internal_core_ports.Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_rickferrdev_gostock_internal_core_ports.Code": {
            "type": "string",
            "enum": [
                "INTERNAL_SERVER_ERROR",
                "BAD_REQUEST",
                "RESOURCE_NOT_FOUND",
                "UNAUTHENTICATED",
                "PERMISSION_DENIED",
                "RESOURCE_CONFLICT",
                "USER_NOT_FOUND",
                "INVALID_PASSWORD",
                "EMAIL_ALREADY_REGISTERED",
                "AUTH_TOKEN_EXPIRED",
                "DATABASE_CONNECTION_FAILED",
                "OPERATION_TIMEOUT"
            ],
            "x-enum-varnames": [
                "CodeInternal",
                "CodeBadRequest",
                "CodeNotFound",
                "CodeUnauthenticated",
                "CodeForbidden",
                "CodeConflict",
                "CodeUserNotFound",
                "CodeInvalidPassword",
                "CodeEmailRegistered",
                "CodeTokenExpired",
                "CodeDatabaseError",
                "CodeTimeout"
            ]
        },
        "github_com_rickferrdev_gostock_internal_core_ports.DTOProduct": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "integer"
                },
                "qtd": {
                    "type": "integer"
                },
                "stock_id": {
                    "type": "string"
                }
            }
        },
        "github_com_rickferrdev_gostock_internal_core_ports.DTORequestCreateProduct": {
            "type": "object",
            "required": [
                "name",
                "price",
                "stock_id"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "minLength": 2
                },
                "price": {
                    "type": "integer",
                    "minimum": 1
                },
                "qtd": {
                    "type": "integer",
                    "minimum": 0
                },
                "stock_id": {
                    "type": "string"
                }
            }
        },
        "github_com_rickferrdev_gostock_internal_core_ports.DTORequestCreateStock": {
            "type": "object",
            "required": [
                "capacity",
                "name"
            ],
            "properties": {
                "capacity": {
                    "type": "integer",
                    "minimum": 1
                },
                "name": {
                    "type": "string",
                    "minLength": 3
                }
            }
        },
        "github_com_rickferrdev_gostock_internal_core_ports.DTORequestUpdateProduct": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "minLength": 2
                },
                "price": {
                    "type": "integer",
                    "minimum": 1
                },
                "qtd": {
                    "type": "integer",
                    "minimum": 0
                },
                "stock_id": {
                    "type": "string"
                }
            }
        },
        "github_com_rickferrdev_gostock_internal_core_ports.DTORequestUpdateStock": {
            "type": "object",
            "required": [
                "capacity",
                "name"
            ],
            "properties": {
                "capacity": {
                    "type": "integer",
                    "minimum": 1
                },
                "name": {
                    "type": "string",
                    "minLength": 3
                }
            }
        },
        "github_com_rickferrdev_gostock_internal_core_ports.DTOResponseAllStock": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_rickferrdev_gostock_internal_core_ports.DTOStock"
                    }
                }
            }
        },
        "github_com_rickferrdev_gostock_internal_core_ports.DTOResponseByIDProduct": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_rickferrdev_gostock_internal_core_ports.DTOProduct"
                }
            }
        },
        "github_com_rickferrdev_gostock_internal_core_ports.DTOResponseByIDStock": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_rickferrdev_gostock_internal_core_ports.DTOStock"
                }
            }
        },
        "github_com_rickferrdev_gostock_internal_core_ports.DTOResponseByStockIDProduct": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_rickferrdev_gostock_internal_core_ports.DTOProduct"
                    }
                }
            }
        },
        "github_com_rickferrdev_gostock_internal_core_ports.DTOResponseCreateProduct": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_rickferrdev_gostock_internal_core_ports.DTOProduct"
                }
            }
        },
        "github_com_rickferrdev_gostock_internal_core_ports.DTOResponseCreateStock": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_rickferrdev_gostock_internal_core_ports.DTOStock"
                }
            }
        },
        "github_com_rickferrdev_gostock_internal_core_ports.DTOStock": {
            "type": "object",
            "properties": {
                "capacity": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "used_capacity": {
                    "type": "integer"
                }
            }
        },
        "github_com_rickferrdev_gostock_internal_core_ports.Error": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/github_com_rickferrdev_gostock_internal_core_ports.Code"
                },
                "err": {},
                "message": {
                    "$ref": "#/definitions/github_com_rickferrdev_gostock_internal_core_ports.Message"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "github_com_rickferrdev_gostock_internal_core_ports.Message": {
            "type": "string",
            "enum": [
                "an unexpected internal error occurred",
                "the requested resource was not found",
                "the provided data is invalid",
                "you must be authenticated to access this resource",
                "you do not have permission to perform this action",
                "user with these details already exists",
                "invalid request parameters",
                "cannot remove a stock that still has registered products",
                "the resource's capacity was exceeded",
                "error processing the standard submission message"
            ],
            "x-enum-varnames": [
                "MsgInternal",
                "MsgNotFound",
                "MsgInvalidInput",
                "MsgUnauthorized",
                "MsgForbidden",
                "MsgUserConflict",
                "MsgBadRequest",
                "MsgStockNotEmpty",
                "MsgCapacityExceeded",
                "MsgProcessingMessage"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
